"""术语表：三态生命周期 + CSV 权威 + 冲突外置 + 注入过滤。"""

from __future__ import annotations

from .csv_io import (
    Glossary,
    entry_to_row,
    load_glossary_csv,
    load_legacy_category_csv,
    normalize,
    read_conflicts_jsonl,
    row_to_entry,
    save_glossary_csv,
    write_conflicts_jsonl,
)
from .models import (
    GENDERS,
    STATUS_CANDIDATE,
    STATUS_CONFIRMED,
    STATUS_CONFLICT,
    STATUS_SEED,
    TERM_STATUSES,
    TERM_TYPES,
    GlossaryConflict,
    GlossaryEntry,
)
from .store import (
    STORE_HEADER,
    MergeResult,
    StoreConflict,
    StoreEntry,
    export_for_workspace,
    load_store_csv,
    merge_workspace_glossary,
    read_store_conflicts,
    save_store_csv,
    store_key,
    store_stats,
    to_workspace_entry,
    unresolved_keys,
    write_store_conflicts,
    write_workspace_terms,
)
from .terms import TerminologyHit, terminology_hits, terms_in_text

__all__ = [
    "GENDERS",
    "STORE_HEADER",
    "Glossary",
    "GlossaryConflict",
    "GlossaryEntry",
    "MergeResult",
    "STATUS_CANDIDATE",
    "STATUS_CONFIRMED",
    "STATUS_CONFLICT",
    "STATUS_SEED",
    "StoreConflict",
    "StoreEntry",
    "TERM_STATUSES",
    "TERM_TYPES",
    "TerminologyHit",
    "entry_to_row",
    "export_for_workspace",
    "load_glossary_csv",
    "load_legacy_category_csv",
    "load_store_csv",
    "merge_workspace_glossary",
    "normalize",
    "read_conflicts_jsonl",
    "read_store_conflicts",
    "row_to_entry",
    "save_glossary_csv",
    "save_store_csv",
    "store_key",
    "store_stats",
    "terminology_hits",
    "terms_in_text",
    "to_workspace_entry",
    "unresolved_keys",
    "write_conflicts_jsonl",
    "write_store_conflicts",
    "write_workspace_terms",
]
